### ISSUE TITLE
Please add ezSpeech (Text To Speech ANE)

### ISSUE THREAD

**Issue by Fabrice-Montfort** [uhub/awesome-actionscript#4]
https://fabricemontfort.com/product/ezspeech-ane-air-native-extension/

Sample code and free demo project+ANE on the page

**Comment by ccding** [comment]
please file a pull request

**Comment by Fabrice-Montfort** [comment]
This is paid extension as ezSTT. Is it a problem ?

**Comment by ccding** [comment]
>  Is it a problem ?

I checked your source code--it is not qualified to be included to this list.
